# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
workflow:
jobs:
  node:
    working_directory: ~/working_directory
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: npm test
          command: |
            npm test
