# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
jobs:
  node:
    working_directory: ~/working_directory
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
        name: test
        command: npm test
      - run:
        name: code-coverage
        command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
        path: test-results.xml
        prefix: tests
      - store_artifacts:
        path: coverage
        prefix: coverage
      - store_test_results:
        path: test-results.xml
workflows:
version: 2.1
